name: Dev build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build-amd64:
    name: Build for Windows x64
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build Fluent-Gmail/Gmail.csproj -c Release -a x64
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows x64 Dev Build
        path: Fluent-Gmail/bin/x64/Release