name: Development Build

on:
  push:
    branches:
      - dev
    paths-ignore:
      - README.md
      - assets/**
  pull_request:
    branches:
      - dev
    paths-ignore:
      - README.md
      - assets/**

env:
  PROJECT_FILE: Gmail.csproj

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:

      - name: Fetch source code
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        shell: pwsh
        run: |
            dotnet build -c Release -a x64 $Env:PROJECT_FILE
            dotnet build -c Release -a arm64 $Env:PROJECT_FILE

      - name: Upload x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows x64 Development Build
          path: bin/Release/net9.0-windows7.0/win-x64

      - name: Upload Arm64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Arm64 Development Build
          path: bin/Release/net9.0-windows7.0/win-arm64