name: Development Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-amd64:
    name: Build for Windows x64
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Build the project
    - name: Build
      run: dotnet build -c Release -a x64 Gmail.csproj
    
    # Upload output binaries
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows x64 Development Build
        path: bin/x64/Release/