name: Development Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_amd64:
    name: Build for Windows AMD64

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build -c Release -a x64 Gmail.csproj

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows AMD64 Development Build
          path: bin/Release/

  build_arm64:
    name: Build for Windows ARM64

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Build the project
      - name: Build
        run: dotnet build -c Release -a arm64 Gmail.csproj

      # Upload output binaries
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows ARM64 Development Build
          path: bin/Release/
