name: Stable Build

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    name: Create a new release draft
    runs-on: windows-latest

    outputs:
      release_tag: ${{ steps.project_version.outputs.TAG }}

    steps:
      - name: Fetch source code
        uses: actions/checkout@v4

      - name: Read AssemblyVersion
        id: project_version
        shell: pwsh
        run: |
          [xml]$xml = Get-Content "Gmail.csproj"
          $assemblyVersion = $xml.Project.PropertyGroup.AssemblyVersion
          Write-Output "TAG=$($assemblyVersion)" >> $Env:GITHUB_OUTPUT

      - name: Draft release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.project_version.outputs.TAG }}
          name: Fluent Gmail v${{ steps.project_version.outputs.TAG }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md

  build_amd64:
    name: Build for Windows x64

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish
        run: dotnet publish -c Release -r win-x64 -p:PublishProfile=release Gmail.csproj

      - name: Compress files
        run: Compress-Archive -Path publish\ -DestinationPath ./Fluent-Gmail_v${{ needs.draft_release.outputs.release_tag }}.zip

      - name: Upload artifact
        run: gh release upload ${{ needs.draft_release.outputs.release_tag }} ./Fluent-Gmail_v${{ needs.draft_release.outputs.release_tag }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
